### ISSUE TITLE
Transpile for lower node version

### ISSUE THREAD

**Issue by Remco75** [subeeshcbabu/swagmock#32]
Hi, thnx for this module, very useful!
But, I face the problem that I cannot you beyond version 0.0.4. My project does not support node 6. And guess a lot of project won't have that yet. 

Can you do a compile to node <6 code (or something?) I think i only breaks on the options object.

**Comment by subeeshcbabu** [comment]
You are missing out mostly API changes like promise support and `validated = true` support
https://github.com/subeeshcbabu/swagmock/blob/master/CHANGELOG.md#v100
If you are OK with using callback style API, I think it is OK to use 0.0.4 

Let me see if I can back port the bug fixes to prev version and release a `0.0.5`. 

I would love to stay away from transpilers like `babel` because it clutters the module and introduces complex dev dependencies and compile steps (Unnecessary for simple modules, from my experience).

**Comment by Remco75** [comment]
@subeeshcbabu thnx for the response. I agree with the cluttering. Downside is random people like me asking to keep another branch of code alive ;-)

 if you could backport the bugifxes that's amazing. and I don't care much for the promise style for now.
Prob nice to mention that this module node 6 only, and point to the 0.0.5 branch in the readme

**Comment by subeeshcbabu** [comment]
Published `0.0.5`. Updated the `readme` with node engine info
